ZMBusService/Controllers/ZMRouteStopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZMBusService.Models;

namespace ZMBusService.Controllers
{
    public class ZMRouteStopController : Controller
    {
        private BusServiceSQLContext db = new BusServiceSQLContext();

        /// <summary>
        /// Passes the list of routestops
        /// </summary>
        /// <param name="routeName">routeName of request routeStops</param>
        /// <param name="routeCode">routeCode of request routeStops</param>
        /// <returns>View along with list of routeStops</returns>
        public ActionResult Index(string routeName, int routeCode = 0)
        {
            if (routeCode != 0 && routeName != null)
            {
                Session["routeCode"] = routeCode;
                Session["routeName"] = routeName;
                string tempRouteCode = Session["routeCode"].ToString();
                var routeStops = db.routeStops.Where(a => a.busRouteCode == tempRouteCode).Include(r => r.busRoute).Include(r => r.busStop).OrderBy(a=>a.offsetMinutes);
                return View(routeStops.ToList());
            }
            else
            {
                if (Session["routeCode"] != null)
                {
                    string tempRouteCode = Session["routeCode"].ToString();
                    var routeStops = db.routeStops.Where(a => a.busRouteCode == tempRouteCode).Include(r => r.busRoute).Include(r => r.busStop).OrderBy(a=>a.offsetMinutes); ;
                    return View(routeStops.ToList());
                }
                else
                {
                    TempData["message"] = "Please select the Show Route corresponding to bus";
                    TempData["messageType"] = "danger";

                    return RedirectToAction("Index", "ZMBusRoute");
                }
            }


        }

        /// <summary>
        /// Passes the complete routeStop model
        /// </summary>
        /// <param name="id">id of the request routeStop</param>
        /// <returns>View along with routeStop model</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            routeStop routestop = db.routeStops.Find(id);
            if (routestop == null)
            {
                return HttpNotFound();
            }
            return View(routestop);
        }

        /// <summary>
        /// Renders create routeStop page
        /// </summary>
        /// <returns>Create routestop view</returns>
        public ActionResult Create()
        {
           // ViewBag.busRouteCode = new SelectList(db.busRoutes, "busRouteCode", "routeName");
            if (Session["routeCode"] != null)
            {
                ViewBag.busStopNumber = new SelectList(db.busStops, "busStopNumber", "location");
                return View();
            }
            else
            {
                TempData["message"] = "Please select the Show Route corresponding to bus";
                TempData["messageType"] = "danger";

                return RedirectToAction("Index", "ZMBusRoute");
            }
           
        }

        /// <summary>
        /// Saves the post back response from the user for create a new route stop
        /// </summary>
        /// <param name="routestop">routeStop model</param>
        /// <returns>View along with routeStop model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="routeStopId,busRouteCode,busStopNumber,offsetMinutes")] routeStop routestop)
        {
            if (ModelState.IsValid)
            {
                routestop.busRouteCode = Session["routeCode"].ToString();
                db.routeStops.Add(routestop);
                db.SaveChanges();
                TempData["message"] = "Record created successfully";
                TempData["messageType"] = "success";
                return RedirectToAction("Index");
            }

            ViewBag.busRouteCode = new SelectList(db.busRoutes, "busRouteCode", "routeName", routestop.busRouteCode);
            ViewBag.busStopNumber = new SelectList(db.busStops, "busStopNumber", "location", routestop.busStopNumber);
            return View(routestop);
        }

        /// <summary>
        /// Renders edit routeStop page
        /// </summary>
        /// <param name="id">id of the request routestop</param>
        /// <returns>View along with route stop model</returns>
        public ActionResult Edit(int? id)
        {
           
            if (Session["routeCode"] != null)
            {
                routeStop routestop = db.routeStops.Find(id);
                ViewBag.busRouteCode = new SelectList(db.busRoutes, "busRouteCode", "routeName", routestop.busRouteCode);
                ViewBag.busStopNumber = new SelectList(db.busStops, "busStopNumber", "location", routestop.busStopNumber);
                return View(routestop);
            }
            else
            {
                TempData["message"] = "Please select the Show Route corresponding to bus";
                TempData["messageType"] = "danger";

                return RedirectToAction("Index", "ZMBusRoute");
            }
            
          
           
        }

        /// <summary>
        /// Saves the post back response from the user for edit route stop
        /// </summary>
        /// <param name="routestop">routeStop model</param>
        /// <returns>View along with routeStop model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="routeStopId,busRouteCode,busStopNumber,offsetMinutes")] routeStop routestop)
        {
            if (ModelState.IsValid)
            {
                routestop.busRouteCode = Session["routeCode"].ToString();
                db.Entry(routestop).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "Record updated successfully";
                TempData["messageType"] = "success";
                return RedirectToAction("Index");
            }
            ViewBag.busRouteCode = new SelectList(db.busRoutes, "busRouteCode", "routeName", routestop.busRouteCode);
            ViewBag.busStopNumber = new SelectList(db.busStops, "busStopNumber", "location", routestop.busStopNumber);
            return View(routestop);
        }

        /// <summary>
        /// Renders delete routeStop page
        /// </summary>
        /// <param name="id">id of the requested routestop for delete</param>
        /// <returns>View along with routeStop model</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            } 
            routeStop routestop = db.routeStops.Find(id);
            if (routestop == null)
            {
                return HttpNotFound();
            }
            return View(routestop);
        }

        /// <summary>
        /// Deletes the routeStop upon confirmation from the user
        /// </summary>
        /// <param name="id">id of the requested routeStop for delete</param>
        /// <returns>Redirects to Index after delete</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            routeStop routestop = db.routeStops.Find(id);
            db.routeStops.Remove(routestop);
            db.SaveChanges();
            TempData["message"] = "Record deleted successfully";
            TempData["messageType"] = "success";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Disposes the db context to free up the memory and closes connection with database
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZMBusService/Controllers/ZMTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZMBusService.Models;
using System.Data.Entity;

namespace ZMBusService.Controllers
{
    public class ZMTripController : Controller
    {
        private BusServiceSQLContext db = new BusServiceSQLContext();

        /// <summary>
        /// Passes the list of trips for the selected bus route
        /// </summary>
        /// <param name="routeCode">bus route of the requested trips</param>
        /// <param name="routeName">route name of the requested trips</param>
        /// <returns>View along with list of trips</returns>
        public ActionResult Index(string routeCode, string routeName)
        {

            if (routeCode == null || routeName == null)
            {
                if (Session["routeCode"] == null && Session["routeName"] == null)
                {
                    TempData["message"] = "Please select the monitored trip link for the route";
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index", "ZMBusRoute");
                }

            }
            else
            {
                Session["routeCode"] = routeCode;
                Session["routeName"] = routeName;
            }
            string sRouteCode = Session["routeCode"].ToString();
            var query = from tr in db.trips
                        join dr in db.drivers
                        on tr.driverId equals dr.driverId
                        join bs in db.buses
                        on tr.busId equals bs.busId
                        join rs in db.routeSchedules
                        on tr.routeScheduleId equals rs.routeScheduleId
                        where (rs.busRouteCode == sRouteCode)
                        orderby tr.tripDate descending, rs.startTime
                        select (new BusTripVM { tripDate = tr.tripDate, startTime = rs.startTime, driverFullName = dr.fullName, busNumber = bs.busNumber, comments = tr.comments });
            return View(query);


        }
        /// <summary>
        ///Renders view for creating trip for the selected bus route
        /// </summary>
        /// <returns>Create trip view</returns>
        public ActionResult Create()
        {
            if (Session["routeCode"] == null && Session["routeName"] == null)//checking if user is following the correct navigation path to create the trip. There chances that user might come directly on create page using link
            {
                TempData["message"] = "Please select the monitored trip link for the route and then click on create link";
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "ZMBusRoute");
            }
            string sRouteCode = Session["routeCode"].ToString();
            ViewBag.routeSchedule = new SelectList(db.routeSchedules.OrderBy(a => a.startTime).Where(a => a.busRouteCode == sRouteCode), "routeScheduleId", "startTime");
            ViewBag.driver = new SelectList(db.drivers.OrderBy(a => a.fullName), "driverId", "fullName");
            ViewBag.bus = db.buses.OrderBy(a => a.busNumber).Where(a => a.status == "available");
            return View();
        }

        /// <summary>
        /// Creates trip record from posted data from trip view
        /// </summary>
        /// <param name="trip">create model received from view</param>
        /// <returns>View along with same saved trip model</returns>
        [HttpPost]
        public ActionResult Create([Bind(Include = "tripId,routeScheduleId,tripDate,driverId,busId, comments")] trip trip)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.trips.Add(trip);
                    db.SaveChanges();
                    TempData["message"] = "Bus trip created succesfully";
                    TempData["messageType"] = "success";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.GetBaseException().ToString()); //getting the base exception and adding to model state error
                }

            }
            string sRouteCode = Session["routeCode"].ToString();
            ViewBag.routeSchedule = new SelectList(db.routeSchedules.OrderBy(a => a.startTime).Where(a => a.busRouteCode == sRouteCode), "routeScheduleId", "startTime");//dropdown for start times
            ViewBag.driver = new SelectList(db.drivers, "driverId", "fullName"); //dropdown for drivers
            ViewBag.bus = db.buses.OrderBy(a => a.busNumber).Where(a => a.status == "available"); //list for creating radio buttons bus number
            return View(trip);

        }
    }
}

ZMBusService/Views/ZMBusRoute/Create.cshtml
@model ZMBusService.Models.busRoute

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    
    <div class="form-horizontal">
        <h4>busRoute</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.busRouteCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.busRouteCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.busRouteCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.routeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.routeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.routeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZMBusService/Views/ZMBusRoute/Delete.cshtml
@model ZMBusService.Models.busRoute

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>busRoute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model=>model.busRouteCode)
        </dt>
      
        <dd>
            @Html.DisplayFor(model=>model.busRouteCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.routeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.routeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZMBusService/Views/ZMBusRoute/Details.cshtml
@model ZMBusService.Models.busRoute

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>busRoute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model=>model.busRouteCode)
        </dt>
      
        <dd>
            @Html.DisplayFor(model=>model.busRouteCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.routeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.routeName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.busRouteCode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZMBusService/Views/ZMBusRoute/Edit.cshtml
@model ZMBusService.Models.busRoute

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>busRoute</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.busRouteCode)
        <div class="form-group">
            @Html.LabelFor(model => model.busRouteCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.busRouteCode, new { htmlAttributes = new { @class = "form-control", @disabled="disabled" } })
            
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.routeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.routeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.routeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZMBusService/Views/ZMBusRoute/Index.cshtml
@model IEnumerable<ZMBusService.Models.busRoute>

    @{
        ViewBag.Title = "Bus Route Listing";
    }

    <h2>@ViewBag.Title</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.busRouteCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.routeName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.busRouteCode)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.routeName)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.busRouteCode }) |
                    @Html.ActionLink("Details", "Details", new { id = item.busRouteCode }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.busRouteCode }) |
                    @Html.ActionLink("Show Routes", "Index", "ZMRouteStop", new { routeCode = item.busRouteCode, routeName = item.routeName }, null) |
                    @Html.ActionLink("Monitored Trips", "Index", "ZMTrip", new { routeCode=item.busRouteCode, routeName=item.routeName},null)
                </td>
            </tr>
        }

    </table>